username: ''           # Username for Plex.tv
password: ''           # Password for Plex.tv
server: ''             # Name of server
devicepathprefix: ''   # For DAC specific on-device location
ignorestring: XXX, YYY # A list of playlists to ignore 
